# Generated by Django 5.2.6 on 2025-11-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazoncito', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_arrival', models.DateTimeField()),
                ('route_path', models.TextField()),
                ('total_distance', models.IntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_estimate', to='amazoncito.order')),
            ],
        ),
    ]
